### ISSUE TITLE
Deployment of FDstore example with AS4 store failed on EKS when docker image is built using installation home

### ISSUE THREAD

**Issue by jgirase** [TIBCOSoftware/be-tools#143]
Steps:
1.Build image of FDStore example with configuration Ignite cluster provider + Ignite cache + AS4 store using existing installation home.
2.Push the image to ECR and perform required AS4 grid setup 
3.Deploy the application using helm chart.
4.Check cache/inference pod logs, it shows below exception,
Its looking for file dbkeywordmap.xml which is not present inside docker image when built using installation.
Exception:
2020 Dec 04 12:18:04.666 GMT Z fdstoreas4-ignite-becacheagent-0 INFO [main] - [as.store] Successfully connected to ActiveSpaces Store with Realm URL http://ftlservers.asdg.svc.cluster.local:30080
2020 Dec 04 12:18:04.669 GMT Z fdstoreas4-ignite-becacheagent-0 FATAL [main] - [as.store] ActiveSpaces BackingStore initialization failed.
java.lang.RuntimeException: Cannot process keyword map file : /opt/tibco/be/6.1/bin/dbkeywordmap.xml
	at com.tibco.be.as.store.ASStoreStartupHelper.loadKeywordMap(ASStoreStartupHelper.java:168)
	at com.tibco.be.as.store.ASStoreStartupHelper.init(ASStoreStartupHelper.java:114)
	at com.tibco.be.as.store.ActiveSpacesStore.initialize(ActiveSpacesStore.java:160)
	at com.tibco.be.as.store.ActiveSpacesStore.<init>(ActiveSpacesStore.java:104)
	at com.tibco.be.as.store.ActiveSpacesStoreProvider.<init>(ActiveSpacesStoreProvider.java:44)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.tibco.cep.runtime.service.store.StoreProviderFactory.getStoreProvider(StoreProviderFactory.java:40)
	at com.tibco.cep.ignite.store.IgniteStoreProvider.init(IgniteStoreProvider.java:97)
	at com.tibco.cep.runtime.service.store.ProxyDaoProvider.initHook(ProxyDaoProvider.java:107)
	at com.tibco.cep.runtime.service.om.impl.AbstractDaoProvider.init(AbstractDaoProvider.java:83)
	at com.tibco.cep.runtime.service.cluster.MultiAgentCluster.init(MultiAgentCluster.java:166)
	at com.tibco.cep.runtime.session.impl.RuleServiceProviderImpl.initCluster(RuleServiceProviderImpl.java:839)
	at com.tibco.cep.runtime.session.impl.RuleServiceProviderImpl.configure(RuleServiceProviderImpl.java:318)
	at com.tibco.cep.container.standalone.BEMain.jumpStart(SourceFile:167)
	at com.tibco.cep.container.standalone.BEMain.main(SourceFile:71)
Caused by: java.io.FileNotFoundException: /opt/tibco/be/6.1/bin/dbkeywordmap.xml (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at com.tibco.be.as.store.ASStoreStartupHelper.loadKeywordMap(ASStoreStartupHelper.java:144)
	... 17 more

Note: Same works fine on premise/local setup.

**Comment by nareshkumarthota** [comment]
fix is available in branch `docker-scripts-improvements`

**Comment by jgirase** [comment]
Verified it with branch docker-scripts-improvements
Find attached logs for reference.
[fdstore_as4_ignite_logs.zip](https://github.com/TIBCOSoftware/be-tools/files/5663977/fdstore_as4_ignite_logs.zip)

**Comment by jgirase** [comment]
already verified so closing it
