### ISSUE TITLE
RMS engine unable to connect to Cassandra DB. Getting java.lang.NoClassDefFoundError: com/google/common/collect/ImmutableMap

### ISSUE THREAD

**Issue by priyanka-nawal** [TIBCOSoftware/be-tools#206]
**Steps to reproduce:**
1. Configure RMS with Ignite_Ignite_Cassandra/FTL_Ignite_Cassandra
2. Deploy Cassandra
3. Update values.yaml file as per CDD configuration
4. Install helm release
5. RMS pod shows below exception while connecting to Cassandra
`2021 Jun 04 05:30:58.280 GMT Z ignite-cassandra-rms-0 INFO [main] - [ignite] Starting Ignite node as 'Server'
2021 Jun 04 05:31:00.289 GMT Z ignite-cassandra-rms-0 INFO [main] - [StoreProviderFactory] Using store provider - 'com.tibco.be.cassandra.CassandraStoreProvider'
2021 Jun 04 05:31:00.355 GMT Z ignite-cassandra-rms-0 FATAL [main] - [container.standalone] null
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.tibco.cep.runtime.service.store.StoreProviderFactory.getStoreProvider(StoreProviderFactory.java:40)
	at com.tibco.cep.ignite.store.IgniteStoreProvider.init(IgniteStoreProvider.java:96)
	at com.tibco.cep.runtime.service.store.ProxyDaoProvider.initHook(ProxyDaoProvider.java:107)
	at com.tibco.cep.runtime.service.om.impl.AbstractDaoProvider.init(AbstractDaoProvider.java:83)
	at com.tibco.cep.runtime.service.cluster.MultiAgentCluster.init(MultiAgentCluster.java:166)
	at com.tibco.cep.runtime.session.impl.RuleServiceProviderImpl.initCluster(RuleServiceProviderImpl.java:843)
	at com.tibco.cep.runtime.session.impl.RuleServiceProviderImpl.configure(RuleServiceProviderImpl.java:314)
	at com.tibco.cep.container.standalone.BEMain.jumpStart(SourceFile:169)
	at com.tibco.cep.container.standalone.BEMain.main(SourceFile:71)
Caused by: java.lang.NoClassDefFoundError: com/google/common/collect/ImmutableMap
	at com.datastax.driver.core.ProtocolVersion.<clinit>(ProtocolVersion.java:80)
	at com.datastax.driver.core.PoolingOptions.<clinit>(PoolingOptions.java:100)
	at com.tibco.be.cassandra.CassandraStoreProvider.initConfig(CassandraStoreProvider.java:465)
	at com.tibco.be.cassandra.CassandraStoreProvider.initConnection(CassandraStoreProvider.java:154)
	at com.tibco.cep.store.custom.StoreInitializer.init(StoreInitializer.java:91)
	at com.tibco.cep.store.custom.BaseStore.initialize(BaseStore.java:285)
	at com.tibco.cep.store.custom.BaseStoreProvider.<init>(BaseStoreProvider.java:95)
	at com.tibco.be.cassandra.CassandraStoreProvider.<init>(CassandraStoreProvider.java:84)
	... 13 more
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.ImmutableMap
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 21 more
[ignite-cassandra-rms-0.log](https://github.com/TIBCOSoftware/be-tools/files/6597227/ignite-cassandra-rms-0.log)
[ignite-cassandra-rms-0-ignite.log](https://github.com/TIBCOSoftware/be-tools/files/6597229/ignite-cassandra-rms-0-ignite.log)
`
After debugging this, observed that lib/ext/tpcl/aws folder is missing from rms pod which contains guava jar required for Cassandra.

**Comment by nareshkumarthota** [comment]
@priyanka-nawal  Can you try once more by pulling latest code from `feature-rms-helm` branch.

**Comment by priyanka-nawal** [comment]
Yes working fine with latest code. Verified with Ignite_Ignite_Cassandra. Attached logs for reference
[Working.zip](https://github.com/TIBCOSoftware/be-tools/files/6599219/Working.zip)
