### ISSUE TITLE
Hot deployment fails sometimes for single RMS instance with "UndeclaredThrowableException" in UI

### ISSUE THREAD

**Issue by priyanka-nawal** [TIBCOSoftware/be-tools#216]
**Below configurations used to reproduce the issue:**
Provisioning type: dynamic
rmsWebstudio: false
RMS: FTL_Ignite_Cassandra
CCA: AS2_AS2_None
RMS Replica: 1

**Steps:**
1. Clean up EFS, PV and PVC
2. Configure RMS yaml to use FTL_Ignite_Cassandra, Replica:1 and Dynamic provisioning. Install RMS release
3. Now modify rmsSharedPVC value in CCA yaml and install CCA release
4. Login to WebStudio, modify deployment preferences for CCA
5. Checkout CCA, Create RTI, Commit and Approve it
6. Now perform hot deployment. It throws "UndeclaredThrowableException" in the UI and below stack trace is observed in CCA inf logs
```
2021 Jul 07 06:53:51.975 GMT Z ccasingle-inferenceagent-0 INFO [RMI TCP Connection(5)-192.168.26.172] - [runtime.service] Cluster [CreditCardApplication] : Hot deployment of rule template instance [/Rule_Templates/RTI1] requested.
2021 Jul 07 06:53:51.993 GMT Z ccasingle-inferenceagent-0 ERROR [RMI TCP Connection(5)-192.168.26.172] - [runtime.service] Error invoking MBean operation
java.lang.Exception: Rule template deploy source dir [/opt/tibco/be/6.1/rms/shared/CreditCardApplication] is not a directory
	at com.tibco.cep.runtime.service.cluster.deploy.util.RuleTemplateInstanceDeployTool.check(RuleTemplateInstanceDeployTool.java:176)
	at com.tibco.cep.runtime.service.cluster.deploy.util.RuleTemplateInstanceDeployTool.deployRuleTemplateInstance(RuleTemplateInstanceDeployTool.java:66)
	at com.tibco.cep.runtime.service.cluster.deploy.RuleTemplateDeployer.loadAndDeployRuleTemplateInstance(RuleTemplateDeployer.java:149)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:260)
	at java.management/com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:112)
	at java.management/com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:46)
	at java.management/com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
	at java.management/com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138)
	at java.management/com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252)
	at java.management/javax.management.StandardMBean.invoke(StandardMBean.java:405)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:809)
	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.tibco.cep.runtime.service.management.jmx.connectors.SecureJMXProxy$MBSFInvocationHandler.invoke(SecureJMXProxy.java:79)
	at com.sun.proxy.$Proxy24.invoke(Unknown Source)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1466)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1307)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1399)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:827)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
Verified shared folder present under RMS pod, RTI was present there but not inside CCA pod shared folder.
Also, it was not present on EFS. Please find the attached logs and other screenshots for reference

**Note: This issue is not consistently reproducible.** 
[Usecase#1.zip](https://github.com/TIBCOSoftware/be-tools/files/6775274/Usecase.1.zip)

**Comment by vpatil-tibco** [comment]
This also seems to be similar to the PV mount sync issues observed in #197

**Comment by rameshpolishetti** [comment]
This is happening due to RMS folder synchronization issue, which is fixed.
@priyanka-nawal  please take latest changes to validate this.

**Comment by priyanka-nawal** [comment]
Verified couple of flows with different Cluster providers with single rms replica and did not encounter the above mentioned issue.
1. Ignite_Ignite_Mysql
2. AS2_AS2_Mysql
3. FTL_Ignite_Cassandra
4. Ignite_Ignite_Cassandra

Attaching logs for reference
[SingleReplica-logs.zip](https://github.com/TIBCOSoftware/be-tools/files/6791892/SingleReplica-logs.zip)
