### ISSUE TITLE
Unable to run bundled BE application SimpleProcess using Container Image.

### ISSUE THREAD

**Issue by athombare** [TIBCOSoftware/be-tools#233]
If user builds a container image using process add-on (AS2 + Enterprise + Process) and Simple Process example artifacts (SimpleProcess.cdd & SimpleProcess.ear). And tries to run Simple Process example, following issues are observed on container engine start.

`Caused by: org.eclipse.emf.ecore.xmi.PackageNotFoundException: Package with uri 'http:///com/tibco/cep/bpmn/core/model/semantic/process/cep-bpmn.ecore' not found. (mem:///1629802981274/Processes/DebugOut.beprocess, 2, 1113)
        at org.eclipse.emf.ecore.xmi.impl.XMLHandler.getPackageForURI(XMLHandler.java:2643)
        at org.eclipse.emf.ecore.xmi.impl.XMLHandler.getFactoryForPrefix(XMLHandler.java:2476)
        at org.eclipse.emf.ecore.xmi.impl.XMLHandler.createObjectByType(XMLHandler.java:1353)
        at org.eclipse.emf.ecore.xmi.impl.XMLHandler.createTopObject(XMLHandler.java:1522)
        at org.eclipse.emf.ecore.xmi.impl.XMLHandler.processElement(XMLHandler.java:1044)
        at org.eclipse.emf.ecore.xmi.impl.XMIHandler.processElement(XMIHandler.java:78)
        at org.eclipse.emf.ecore.xmi.impl.XMLHandler.startElement(XMLHandler.java:1026)
        at org.eclipse.emf.ecore.xmi.impl.XMLHandler.startElement(XMLHandler.java:720)
        at org.eclipse.emf.ecore.xmi.impl.XMIHandler.startElement(XMIHandler.java:190)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:510)
        at java.xml/com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.startElement(XMLDTDValidator.java:731)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1397)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$ContentDriver.scanRootElementHook(XMLDocumentScannerImpl.java:1292)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3063)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:836)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:324)
        at org.eclipse.emf.ecore.xmi.impl.XMLLoadImpl.load(XMLLoadImpl.java:175)
        ... 17 more
`

Also Engines are not able to process events. 

`INFO: Starting Servlet engine: [Apache Tomcat/9.0.35]
2021 Aug 24 11:03:19.061 GMT Z be-engine INFO [HTTP-Channel-Startup] - [driver.http] Channel server for HTTP Channel[Port:8090] starting
Aug 24, 2021 11:03:19 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-nio-8090"]
2021 Aug 24 11:03:19.067 GMT Z be-engine INFO [HTTP-Channel-Startup] - [driver.http] Channel server for HTTP Channel[Port:8090] successfully started
2021 Aug 24 11:38:40.201 GMT Z be-engine WARN [$default.be.mt$.Thread.1] - [bpmn.runtime] [ProcessAgent] No starter process configured with this class of object : class be.gen.Events.CreateCustomerEvent
`

The issue can be observed with latest GA i.e 6.1.1 and 6.0.0

[600.log](https://github.com/TIBCOSoftware/be-tools/files/7043763/600.log)
[600BuildImage.log](https://github.com/TIBCOSoftware/be-tools/files/7043764/600BuildImage.log)

**Comment by LakshmiMekala** [comment]
@athombare We identified a temporary fix for this error. Can you make below mentioned code changes in your scripts.

When building docker image from installers- https://github.com/TIBCOSoftware/be-tools/blob/master/cloud/docker/lib/prepare_finalimage.sh comment line no: 49&56

When building docker image from localinstallation - https://github.com/TIBCOSoftware/be-tools/blob/master/cloud/docker/build_image.sh  comment line no :806&812.

Let us know if it works for you.

We are working on permanent fix for this issue

**Comment by athombare** [comment]
@LakshmiMekala I tried both the workarounds. They seem to be working for the issue..
[Workaround.zip](https://github.com/TIBCOSoftware/be-tools/files/7081433/Workaround.zip)

**Comment by LakshmiMekala** [comment]
Closing the issue as per above comments
