### ISSUE TITLE
be-q.jar should be part of default jars while building optimized docker image

### ISSUE THREAD

**Issue by AdittyThakare** [TIBCOSoftware/be-tools#244]
Built optimized docker image for bundled FraudDetectionCache(FTLClusterStore.cdd) by providing modules as http, ftl, ignite. 
./build_image.sh -i app -a /home/apps/Aditty/docker/target -s /home/apps/Aditty/docker/Inst -t opt:fdcftl_docker --optimize http,ftl,ignite

Cache engine fails with ""java.lang.NoClassDefFoundError: com/tibco/cep/query/aggregate/AggregateFunctionsProvider.
`2021 Oct 22 13:16:29.899 GMT Z be-engine FATAL [main] - [container.standalone] com/tibco/cep/query/aggregate/AggregateFunctionsProvider
java.lang.NoClassDefFoundError: com/tibco/cep/query/aggregate/AggregateFunctionsProvider
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at com.tibco.cep.ignite.store.IgniteStoreProvider.init(IgniteStoreProvider.java:115)
	at com.tibco.cep.runtime.service.store.ProxyDaoProvider.initHook(ProxyDaoProvider.java:107)
	at com.tibco.cep.runtime.service.om.impl.AbstractDaoProvider.init(AbstractDaoProvider.java:82)
	at com.tibco.cep.runtime.service.cluster.MultiAgentCluster.init(MultiAgentCluster.java:166)
	at com.tibco.cep.runtime.session.impl.RuleServiceProviderImpl.initCluster(RuleServiceProviderImpl.java:804)
	at com.tibco.cep.runtime.session.impl.RuleServiceProviderImpl.configure(RuleServiceProviderImpl.java:306)
	at com.tibco.cep.container.standalone.BEMain.jumpStart(SourceFile:167)
	at com.tibco.cep.container.standalone.BEMain.main(SourceFile:71)
Caused by: java.lang.ClassNotFoundException: com.tibco.cep.query.aggregate.AggregateFunctionsProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 17 more`

The exception is coming because be-q.jar is missing. The jar should be added by default during image build. It would be difficult for customer to understand that query module is also to be added for basic non-query projects image build.

Attaching log for reference.
[fdc_cache_docker.txt](https://github.com/TIBCOSoftware/be-tools/files/7397560/fdc_cache_docker.txt)

**Comment by rameshpolishetti** [comment]
Closing the issue as it is tested and merged to master.
