### ISSUE TITLE
RMS Server image - studio-tools not work (ear and class files created)

### ISSUE THREAD

**Issue by umueller-de** [TIBCOSoftware/be-tools#255]
### Version Information
| Software       | Version(s)     |
| -------------- | -------------- |
| BusinessEvents |  6.2.1              |
| OS Type?       |     Linux           |
| OS Version?    |    Ubuntu  20.04           |
| Docker         |    Windows Docker Desktop            |

Issue:
=====
Studio-tools not work when build the RMS server image (tested with windows docker scripts) with latest BE version 6.2.1. 
Command:
build_image.bat -i rms -s "<installfilesDirectory>"  -t "rms621:v01" -d dockerfiles\Dockerfile-rms 

Start container:
docker run -it --rm -p 8090:8090 -p 5555:5555 -e PU=default -e ENGINE_NAME=rms_server rms621:v01

You able to connect to WebStudio but class- or ear files not build correctly (no errors in WebStudio but ear/class files missing in deployment folder /opt/tibco/be/6.2/rms/shared/<application>.

To test you can connect to the container (docker -exec -it <id> bash) and try to start studio-tools.
cd /opt/tibco/be/6.2/studio/bin
./studio-tools -help

--> ClassNotFound errors returned (see below)

Note:
The issue caused by missing libraries in /opt/tibco/be/6.2/lib/ext/tpcl/apache folder. 
It works when you copy the jar files from a working local installation to the docker container.

Sample docker file (copied files from BE_HOME/lib/ext/tpcl/apache to apache folder):

FROM rms621:v01 as intermediate
COPY apache/* /opt/tibco/be/6.2/lib/ext/tpcl/apache

Exact error (studio-tools -help):
===================
root@da1bd9eecd39:/home/tibco/be# cd /opt/tibco/be/6.2/studio/bin
root@da1bd9eecd39:/opt/tibco/be/6.2/studio/bin# ./studio-tools -help
org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
org.eclipse.m2e.logback.configuration: Logback config file: /opt/tibco/be/6.2/studio/workspace/.metadata/.plugins/org.eclipse.m2e.logback.configuration/logback.1.16.0.20200318-1040.xml
org.eclipse.m2e.logback.configuration: Initializing logback
org.eclipse.core.runtime.CoreException: Plug-in com.tibco.cep.decision.table.core was unable to load class com.tibco.cep.decision.cli.GenerateDecisionTableClassCLI.
        at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:212)
        at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:198)
        at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:923)
        at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
        at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
        at com.tibco.cep.studio.cli.studiotools.StudioCommandLineInterpreter.initializeInterpreters(Unknown Source)
        at com.tibco.cep.studio.cli.studiotools.StudioCommandLineInterpreter.<clinit>(Unknown Source)
        at com.tibco.cep.studio.cli.studiotools.StudioToolsApplication.start(Unknown Source)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
Caused by: java.lang.ClassNotFoundException: An error occurred while automatically activating bundle com.tibco.cep.decision.table.core (942).
        at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:126)
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:572)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:346)
        at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:398)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:477)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:616)
        at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:196)
        ... 19 more
Caused by: org.osgi.framework.BundleException: Error starting module. osgi.identity; type="osgi.bundle"; version:Version="6.2.1.011"; osgi.identity="com.tibco.cep.decision.table.core"; singleton:="true" [id=942]
        at org.eclipse.osgi.container.Module.doStart(Module.java:614)
        at org.eclipse.osgi.container.Module.start(Module.java:468)
        at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:506)
        at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
        ... 27 more
Caused by: java.lang.NoClassDefFoundError: com/tibco/cep/studio/core/index/update/IStudioModelChangedListener
        at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
        at java.base/java.lang.Class.getConstructor0(Class.java:3342)
        at java.base/java.lang.Class.getConstructor(Class.java:2151)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.loadBundleActivator(BundleContextImpl.java:797)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:749)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1011)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365)
        at org.eclipse.osgi.container.Module.doStart(Module.java:605)
        ... 30 more
Caused by: java.lang.ClassNotFoundException: An error occurred while automatically activating bundle com.tibco.cep.studio.core (964).
        at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:126)
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:572)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:346)
        at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:398)
        at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:473)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 39 more
Caused by: org.osgi.framework.BundleException: Exception in com.tibco.cep.studio.core.StudioCorePlugin.start() of bundle com.tibco.cep.studio.core.
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:835)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:763)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1011)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365)
        at org.eclipse.osgi.container.Module.doStart(Module.java:605)
        at org.eclipse.osgi.container.Module.start(Module.java:468)
        at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:506)
        at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
        ... 46 more
Caused by: java.lang.NoClassDefFoundError: org/apache/poi/util/IOUtils
        at com.tibco.cep.studio.core.StudioCorePlugin.start(Unknown Source)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:814)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:806)
        ... 53 more
Caused by: java.lang.ClassNotFoundException: org.apache.poi.util.IOUtils cannot be found by com.tibco.cep.studio.core_6.2.1.011
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:516)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 58 more
An error has occurred. See the log file
/opt/tibco/be/6.2/studio/workspace/.metadata/.log.
root@da1bd9eecd39:/opt/tibco/be/6.2/studio/bin#

**Comment by nareshkumarthota** [comment]
We have addressed this Issue in PR #258

**Comment by vpatil-tibco** [comment]
@umueller-de What is the purpose of using studio-tool off the image. It was not included in the image for it to be used directly as a cli tool. The only reason its there is because RMS has a dependency on it for one feature, else we would have excluded it altogether, like we do it doe the Base BE image.

Studio-tools CLI should be used off the installation only.

@ykalidin / @nareshkumarthota - Check if WebStudio generate deployable is working. If that is failing then we will need to fix it, however if that functionality is working off WebStudio, then we are good.

**Comment by nareshkumarthota** [comment]
@umueller-de  Required changes moved to master now. Please validate from your end and close this issue.

**Comment by umueller-de** [comment]
Confirm issue fixed.
