### ISSUE TITLE
Perl script used to generate props file contains invalid java.extended.property

### ISSUE THREAD

**Issue by mmussett** [TIBCOSoftware/be-tools#357]
### Version Information
| Software       | Version(s)     |
| -------------- | -------------- |
| BusinessEvents |    6.2.2            |
| OS Type?       |     GKE          |
| OS Version?    |  GKE |
| Docker         |                |
| Kubernetes     |    Yes            |
| Helm           |        Yes        |

### What is the expected behavior?
IA starts without NPE when configured with Open Telemetry OTLP type
### What is the actual behavior?
NPE thrown and IA fails

### Other notes on how to reproduce the issue?
When tra.java.extended.property is set via environment through Helm chart and it contains hard coded path to the cep-base.jar rather than %BE_HOME% then the perl script generates incorrect value for java.extended.properties with the javaagent to be removed.

### If the bug is confirmed, would you be willing to submit a PR?
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by mmussett** [comment]
Defect validated with Ulf from support.

**Comment by umueller-de** [comment]
Some more details to the issue:
Perl script "be_docker_run.pm" that extracts tra.java.extended.properties corrupts the value when a full path added as a reference for the java agent.

**e.g.,**
Input:
`tra.java.extended.properties=-Xms1024m -Xmx1024m -javaagent:/opt/tibco/be/6.2/lib/cep-base.jar`

**Output:**
```
grep tra.java.extended.properties beprops_all.props 
tra.java.extended.properties=/opt/tibco/be/6.2/lib/cep-base.jar -XX:MaxMetaspaceSize=256m

cat /opt/tibco/be/6.2/bin/be-engine.tra
...
tra.java.extended.properties=/opt/tibco/be/6.2/lib/cep-base.jar -XX:MaxMetaspaceSize=256m
```
**Test (same operations as done in /home/tibco/be/run script):**
_- Connect to running pod_
```
cd /home/tibco/be
CURRENT_DIR=$(pwd)
BE_PROPS_FILE=beprops_all.props
APP_HOME=/opt/tibco/be/application
# set tra.java.extended.properties if not set already
env tra.java.extended.properties="-Xms1024m -Xmx1024m -Xss2m -javaagent:/opt/tibco/be/6.2/lib/cep-base.jar -XX:MaxMetaspaceSize=256m" bash

export PERL5LIB="/home/tibco/be"
perl -Mbe_docker_run -e "be_docker_run::makeBeProps('testSupport.prop','$APP_HOME','$BE_HOME/')"
```

Result (**_extracted only values after "-javaagent:_**")
```
grep tra.java.extended.properties testSupport.prop
tra.java.extended.properties=/opt/tibco/be/6.2/lib/cep-base.jar -XX:MaxMetaspaceSize=256m
```

**Note**:
The property set correctly using %BE_HOME% instead of the full path for cep-base.jar
`env tra.java.extended.properties="-Xms1024m -Xmx1024m -Xss2m -javaagent:%BE_HOME%/lib/cep-base.jar -XX:MaxMetaspaceSize=256m" bash`

With above settings you able to start an agent when Telemetry not enabled, if enabled the CacheAgent will not start (NullPointer exception).

```
2024 Jul 23 11:42:26:720 GMT +02 cache1-fd FATAL [main] - [container.standalone] null
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.tibco.cep.runtime.session.impl.RuleServiceProviderImpl.initOpenTelemetry(RuleServiceProviderImpl.java:1180)
	at com.tibco.cep.runtime.session.impl.RuleServiceProviderImpl.initCluster(RuleServiceProviderImpl.java:829)
	at com.tibco.cep.runtime.session.impl.RuleServiceProviderImpl.configure(RuleServiceProviderImpl.java:306)
	at com.tibco.cep.container.standalone.BEMain.jumpStart(SourceFile:167)
	at com.tibco.cep.container.standalone.BEMain.main(SourceFile:71)
Caused by: java.lang.NullPointerException
	at net.bytebuddy.agent.builder.AgentBuilder$Default.doInstall(AgentBuilder.java:10254)
	at net.bytebuddy.agent.builder.AgentBuilder$Default.installOn(AgentBuilder.java:10156)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Delegator.installOn(AgentBuilder.java:11790)
	at com.tibco.cep.telemetry.trace.DefaultIntrumentLoader.load(DefaultIntrumentLoader.java:39)
	at com.tibco.cep.telemetry.TelemetryService.lambda$instrument$1(TelemetryService.java:90)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at com.tibco.cep.telemetry.TelemetryService.instrument(TelemetryService.java:90)
	at com.tibco.cep.telemetry.TelemetryService.init(TelemetryService.java:52)
	... 9 more
```

**Comment by mmussett** [comment]
<b>;tldr</b>

Setting this: 

`tra.java.extended.properties="-Xms1024m -Xmx1024m -Xss2m -javaagent:/opt/tibco/be/6.2/lib/cep-base.jar -XX:MaxMetaspaceSize=256m"`

Results in this being written to the props file: 

`tra.java.extended.properties=/opt/tibco/be/6.2/lib/cep-base.jar -XX:MaxMetaspaceSize=256m`

Whereas, setting:

`tra.java.extended.properties="-Xms1024m -Xmx1024m -Xss2m -javaagent:%BE_HOME%/lib/cep-base.jar -XX:MaxMetaspaceSize=256m`

Results in this being written to the props file:

`tra.java.extended.properties=-Xms1024m -Xmx1024m -javaagent:/opt/tibco/be/6.2/lib/cep-base.jar`
